-- Generated by Oracle SQL Developer Data Modeler 17.2.0.188.1059
--   at:        2017-09-28 23:45:14 BST
--   site:      Oracle9i
--   type:      Oracle9i

CREATE TABLE anti2cons (
    antibody_antibody_id       INTEGER NOT NULL,
    consensus_motif_motif_id   INTEGER NOT NULL
)
;

ALTER TABLE anti2cons ADD CONSTRAINT anti2cons_pk PRIMARY KEY ( antibody_antibody_id,consensus_motif_motif_id );

CREATE TABLE antibody (
    antibody_id   INTEGER NOT NULL,
    name          VARCHAR(70)
)
;

ALTER TABLE antibody ADD CONSTRAINT antibody_pk PRIMARY KEY ( antibody_id );

CREATE TABLE average_deviation (
    deviation_id               INTEGER NOT NULL,
    element_num                INTEGER,
    median                     FLOAT,
    average                    FLOAT,
    std_dev                    FLOAT,
    experiment_experiment_id   INTEGER NOT NULL,
    consensus_motif_motif_id   INTEGER NOT NULL
)
;

ALTER TABLE average_deviation ADD CONSTRAINT average_deviation_pk PRIMARY KEY ( deviation_id );

CREATE TABLE cell_lines (
    cellline_id   INTEGER NOT NULL,
    name          VARCHAR(70)
)
;

ALTER TABLE cell_lines ADD CONSTRAINT cell_lines_pk PRIMARY KEY ( cellline_id );

CREATE TABLE consensus_motif (
    motif_id      INTEGER NOT NULL,
    name          VARCHAR(70),
    jaspar_code   VARCHAR(70),
    motif_url     VARCHAR(300),
    length        INTEGER,
    logo          VARCHAR(300)
)
;

ALTER TABLE consensus_motif ADD CONSTRAINT consensus_motif_pk PRIMARY KEY ( motif_id );

CREATE TABLE denovo_motif (
    sequence_id                INTEGER NOT NULL,
    consensus_equence          VARCHAR(70),
    experiment_experiment_id   INTEGER NOT NULL,
    know_motif_finding         VARCHAR(300)
)
;

ALTER TABLE denovo_motif ADD CONSTRAINT denovo_motif_pk PRIMARY KEY ( sequence_id );

CREATE TABLE experiment (
    experiment_id                             INTEGER NOT NULL,
    name                                      VARCHAR(70),
    sra_url                                   VARCHAR(300),
    is_it_paired_end                          CHAR(1),
    sra_record_url                            VARCHAR(300),
    unique_pos                                INTEGER,
    total_tags                                INTEGER,
    fragment_estimate                         INTEGER,
    peak_size_estimate                        FLOAT,
    tags_per_bp                               FLOAT,
    avg_tags_per_pos                          FLOAT,
    avg_tag_length                            FLOAT,
    avg_fragment_GC                           FLOAT,
    total_peaks                               INTEGER,
    peak_size                                 INTEGER,
    total_tags_in_peaks                       FLOAT,
    expected_tags_per_peak                    FLOAT,
    putative_peaks                            INTEGER,
    p_peaks_filt_by_local_signal              INTEGER,
    p_peaks_filt_too_clonal                   INTEGER,
    peaks_after_filtering                     INTEGER,
    genome_genome_id                          INTEGER NOT NULL,
    cell_lines_cellline_id                    INTEGER NOT NULL,
    antibody_antibody_id                      INTEGER NOT NULL,
    exp_type                                  VARCHAR(10)
)
;

ALTER TABLE experiment ADD CONSTRAINT experiment_pk PRIMARY KEY ( experiment_id );

CREATE TABLE genome (
    genome_id    INTEGER NOT NULL,
    short_code   VARCHAR(10),
    species      VARCHAR(70),
    version      VARCHAR(70)
)
;

ALTER TABLE genome ADD CONSTRAINT genome_pk PRIMARY KEY ( genome_id );

CREATE TABLE motif_pos (
    motifpos_id                INTEGER NOT NULL,
    chr                        VARCHAR(2),
    start                      INTEGER,
    end                        INTEGER,
    strand                     VARCHAR(1),
    homer_score                FLOAT,
    trivial                    CHAR(1),
    consensus_motif_motif_id   INTEGER NOT NULL
)
;

ALTER TABLE motif_pos ADD CONSTRAINT motif_pos_pk PRIMARY KEY ( motifpos_id );

CREATE TABLE peak (
    peak_id                    INTEGER NOT NULL,
    chromosome                 VARCHAR(2),
    start                      INTEGER,
    end                        INTEGER,
    norm_tag_count             FLOAT,
    focus_ratio                FLOAT,
    findpeaks_score            FLOAT,
    foldchange_vs_local        FLOAT,
    pvalue                     FLOAT,
    clonal_foldchange          FLOAT,
    experiment_experiment_id   INTEGER NOT NULL
)
;

ALTER TABLE peak ADD CONSTRAINT peak_pk PRIMARY KEY ( peak_id );

CREATE TABLE summit (
    summit_id               INTEGER NOT NULL,
    chr                     VARCHAR(2),
    position                INTEGER,
    distance                INTEGER,
    hight                   INTEGER,
    motif_pos_motifpos_id   INTEGER NOT NULL,
    peak_peak_id            INTEGER NOT NULL
)
;

ALTER TABLE summit ADD CONSTRAINT summit_pk PRIMARY KEY ( summit_id );

ALTER TABLE anti2cons
    ADD CONSTRAINT anti2cons_antibody_fk FOREIGN KEY ( antibody_antibody_id )
        REFERENCES antibody ( antibody_id );

ALTER TABLE anti2cons
    ADD CONSTRAINT anti2cons_consensus_motif_fk FOREIGN KEY ( consensus_motif_motif_id )
        REFERENCES consensus_motif ( motif_id );

ALTER TABLE average_deviation
    ADD CONSTRAINT avg_dev_cons_motif_fk FOREIGN KEY ( consensus_motif_motif_id )
        REFERENCES consensus_motif ( motif_id );

ALTER TABLE average_deviation
    ADD CONSTRAINT avg_dev_exp_fk FOREIGN KEY ( experiment_experiment_id )
        REFERENCES experiment ( experiment_id );

ALTER TABLE denovo_motif
    ADD CONSTRAINT denovo_motif_experiment_fk FOREIGN KEY ( experiment_experiment_id )
        REFERENCES experiment ( experiment_id );

ALTER TABLE experiment
    ADD CONSTRAINT experiment_antibody_fk FOREIGN KEY ( antibody_antibody_id )
        REFERENCES antibody ( antibody_id );

ALTER TABLE experiment
    ADD CONSTRAINT experiment_cell_lines_fk FOREIGN KEY ( cell_lines_cellline_id )
        REFERENCES cell_lines ( cellline_id );

ALTER TABLE experiment
    ADD CONSTRAINT experiment_genome_fk FOREIGN KEY ( genome_genome_id )
        REFERENCES genome ( genome_id );

ALTER TABLE motif_pos
    ADD CONSTRAINT motif_pos_consensus_motif_fk FOREIGN KEY ( consensus_motif_motif_id )
        REFERENCES consensus_motif ( motif_id );

ALTER TABLE peak
    ADD CONSTRAINT peak_experiment_fk FOREIGN KEY ( experiment_experiment_id )
        REFERENCES experiment ( experiment_id );

ALTER TABLE summit
    ADD CONSTRAINT summit_motif_pos_fk FOREIGN KEY ( motif_pos_motifpos_id )
        REFERENCES motif_pos ( motifpos_id );

ALTER TABLE summit
    ADD CONSTRAINT summit_peak_fk FOREIGN KEY ( peak_peak_id )
        REFERENCES peak ( peak_id );
