-- Generated by Oracle SQL Developer Data Modeler 17.2.0.188.1059
--   at:        2019-03-25 23:26:19 GMT
--   site:      Oracle9i
--   type:      Oracle9i



CREATE TABLE anti2cons (
    antibody_antibody_id       INTEGER NOT NULL,
    consensus_motif_motif_id   INTEGER NOT NULL
)
    ;

ALTER TABLE anti2cons ADD CONSTRAINT anti2cons_pk PRIMARY KEY ( antibody_antibody_id,consensus_motif_motif_id );

CREATE TABLE antibody (
    antibody_id      INTEGER NOT NULL,
    name             VARCHAR(70),
    r_shape          INTEGER,
    colour_hex       VARCHAR(10),
    colour_r         INTEGER,
    colour_g         INTEGER,
    colour_b         INTEGER,
    is_it_cofactor   VARCHAR(10)
)
    ;

ALTER TABLE antibody ADD CONSTRAINT antibody_pk PRIMARY KEY ( antibody_id );

CREATE TABLE average_deviation (
    deviation_id               INTEGER NOT NULL,
    element_num                INTEGER,
    median                     FLOAT,
    average                    FLOAT,
    std_dev                    FLOAT,
    experiment_experiment_id   INTEGER NOT NULL,
    consensus_motif_motif_id   INTEGER NOT NULL,
    average_deviation_name     TEXT
)
    ;

ALTER TABLE average_deviation ADD CONSTRAINT average_deviation_pk PRIMARY KEY ( deviation_id );

CREATE TABLE cell_lines (
    cellline_id   INTEGER NOT NULL,
    name          VARCHAR(70)
)
    ;

ALTER TABLE cell_lines ADD CONSTRAINT cell_lines_pk PRIMARY KEY ( cellline_id );

CREATE TABLE consensus_motif (
    motif_id      INTEGER NOT NULL,
    name          VARCHAR(70),
    jaspar_code   VARCHAR(70),
    motif_url     VARCHAR(300),
    length        INTEGER,
    logo          VARCHAR(300)
)
    ;

ALTER TABLE consensus_motif ADD CONSTRAINT consensus_motif_pk PRIMARY KEY ( motif_id );

CREATE TABLE dbsnp (
    dbsnp_id   VARCHAR(20) NOT NULL,
    chr        VARCHAR(2),
    start      INTEGER,
    ref        VARCHAR(300),
    alt        VARCHAR(1000)
)
    ;

ALTER TABLE dbsnp ADD CONSTRAINT dbsnp_pk PRIMARY KEY ( dbsnp_id );

CREATE TABLE denovo_motif (
    sequence_id                INTEGER NOT NULL,
    consensus_sequence         VARCHAR(300),
    experiment_experiment_id   INTEGER NOT NULL,
    know_motif_finding         VARCHAR(300)
)
    ;

ALTER TABLE denovo_motif ADD CONSTRAINT denovo_motif_pk PRIMARY KEY ( sequence_id );

CREATE TABLE experiment (
    experiment_id                             INTEGER NOT NULL,
    name                                      VARCHAR(70),
    sra_url                                   VARCHAR(1500),
    is_it_paired_end                          CHAR(1),
    sra_record_url                            VARCHAR(300),
    unique_pos                                INTEGER,
    total_tags                                INTEGER,
    fragment_estimate                         INTEGER,
    peak_size_estimate                        FLOAT,
    tags_per_bp                               FLOAT,
    avg_tags_per_pos                          FLOAT,
    avg_tag_length                            FLOAT,
    avg_fragment_GC                           FLOAT,
    total_peaks                               INTEGER,
    peak_size                                 INTEGER,
    total_tags_in_peaks                       FLOAT,
    expected_tags_per_peak                    FLOAT,
    putative_peaks                            INTEGER,
    p_peaks_filt_by_local_signal              INTEGER,
    p_peaks_filt_too_clonal                   INTEGER,
    peaks_after_filtering                     INTEGER,
    genome_genome_id                          INTEGER NOT NULL,
    cell_lines_cellline_id                    INTEGER NOT NULL,
    antibody_antibody_id                      INTEGER NOT NULL,
    exp_type                                  VARCHAR(10)
)
    ;

ALTER TABLE experiment ADD CONSTRAINT experiment_pk PRIMARY KEY ( experiment_id );

CREATE TABLE genome (
    genome_id    INTEGER NOT NULL,
    short_code   VARCHAR(10),
    species      VARCHAR(70),
    version      VARCHAR(70)
)
    ;

ALTER TABLE genome ADD CONSTRAINT genome_pk PRIMARY KEY ( genome_id );

CREATE TABLE motif_pos (
    motifpos_id                INTEGER NOT NULL,
    chr                        VARCHAR(2),
    start                      INTEGER,
    end                        INTEGER,
    strand                     VARCHAR(1),
    homer_score                FLOAT,
    trivial                    CHAR(1),
    consensus_motif_motif_id   INTEGER NOT NULL
)
    ;

ALTER TABLE motif_pos ADD CONSTRAINT motif_pos_pk PRIMARY KEY ( motifpos_id );

CREATE TABLE paired_shift_view (
    count                      INTEGER,
    distance                   INTEGER,
    experiment_experiment_id   INTEGER NOT NULL,
    consensus_motif_motif_id   INTEGER NOT NULL
)
    ;

CREATE TABLE peak (
    peak_id                    INTEGER NOT NULL,
    chr                        VARCHAR(2),
    start                      INTEGER,
    end                        INTEGER,
    norm_tag_count             FLOAT,
    focus_ratio                FLOAT,
    findpeaks_score            FLOAT,
    foldchange_vs_local        FLOAT,
    pvalue                     FLOAT,
    clonal_foldchange          FLOAT,
    experiment_experiment_id   INTEGER NOT NULL
)
    ;

ALTER TABLE peak ADD CONSTRAINT peak_pk PRIMARY KEY ( peak_id );

CREATE TABLE pfm (
    position                   SMALLINT,
    proba                      FLOAT,
    probc                      FLOAT,
    probg                      FLOAT,
    probt                      FLOAT,
    consensus_motif_motif_id   INTEGER NOT NULL
)
    ;

CREATE TABLE reference (
    chr                VARCHAR(2),
    start              INTEGER,
    end                INTEGER,
    seq                VARCHAR(200),
    genome_genome_id   INTEGER NOT NULL
)
    ;

CREATE TABLE summit (
    summit_id               INTEGER NOT NULL,
    chr                     VARCHAR(2),
    position                INTEGER,
    distance                INTEGER,
    hight                   FLOAT,
    motif_pos_motifpos_id   INTEGER NOT NULL,
    peak_peak_id            INTEGER NOT NULL
)
    ;

ALTER TABLE summit ADD CONSTRAINT summit_pk PRIMARY KEY ( summit_id );

CREATE TABLE venn_view (
    experiment_experiment_id   INTEGER NOT NULL,
    peak_peak_id               INTEGER NOT NULL,
    summit_summit_id           INTEGER NOT NULL,
    motif_pos_motifpos_id      INTEGER NOT NULL,
    consensus_motif_motif_id   INTEGER NOT NULL
)
    ;

ALTER TABLE anti2cons
    ADD CONSTRAINT anti2cons_antibody_fk FOREIGN KEY ( antibody_antibody_id )
        REFERENCES antibody ( antibody_id );

ALTER TABLE anti2cons
    ADD CONSTRAINT anti2cons_consensus_motif_fk FOREIGN KEY ( consensus_motif_motif_id )
        REFERENCES consensus_motif ( motif_id );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE average_deviation
    ADD CONSTRAINT avg_dev_cons_motif_fk FOREIGN KEY ( consensus_motif_motif_id )
        REFERENCES consensus_motif ( motif_id );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE average_deviation
    ADD CONSTRAINT avg_dev_exp_fk FOREIGN KEY ( experiment_experiment_id )
        REFERENCES experiment ( experiment_id );

ALTER TABLE denovo_motif
    ADD CONSTRAINT denovo_motif_experiment_fk FOREIGN KEY ( experiment_experiment_id )
        REFERENCES experiment ( experiment_id );

ALTER TABLE experiment
    ADD CONSTRAINT experiment_antibody_fk FOREIGN KEY ( antibody_antibody_id )
        REFERENCES antibody ( antibody_id );

ALTER TABLE experiment
    ADD CONSTRAINT experiment_cell_lines_fk FOREIGN KEY ( cell_lines_cellline_id )
        REFERENCES cell_lines ( cellline_id );

ALTER TABLE experiment
    ADD CONSTRAINT experiment_genome_fk FOREIGN KEY ( genome_genome_id )
        REFERENCES genome ( genome_id );

ALTER TABLE motif_pos
    ADD CONSTRAINT motif_pos_consensus_motif_fk FOREIGN KEY ( consensus_motif_motif_id )
        REFERENCES consensus_motif ( motif_id );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE paired_shift_view
    ADD CONSTRAINT paired_shift_cons_motif_fk FOREIGN KEY ( consensus_motif_motif_id )
        REFERENCES consensus_motif ( motif_id );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE paired_shift_view
    ADD CONSTRAINT paired_shift_exp_fk FOREIGN KEY ( experiment_experiment_id )
        REFERENCES experiment ( experiment_id );

ALTER TABLE peak
    ADD CONSTRAINT peak_experiment_fk FOREIGN KEY ( experiment_experiment_id )
        REFERENCES experiment ( experiment_id );

ALTER TABLE pfm
    ADD CONSTRAINT pfm_consensus_motif_fk FOREIGN KEY ( consensus_motif_motif_id )
        REFERENCES consensus_motif ( motif_id );

ALTER TABLE reference
    ADD CONSTRAINT reference_genome_fk FOREIGN KEY ( genome_genome_id )
        REFERENCES genome ( genome_id );

ALTER TABLE summit
    ADD CONSTRAINT summit_motif_pos_fk FOREIGN KEY ( motif_pos_motifpos_id )
        REFERENCES motif_pos ( motifpos_id );

ALTER TABLE summit
    ADD CONSTRAINT summit_peak_fk FOREIGN KEY ( peak_peak_id )
        REFERENCES peak ( peak_id );

ALTER TABLE venn_view
    ADD CONSTRAINT venn_view_consensus_motif_fk FOREIGN KEY ( consensus_motif_motif_id )
        REFERENCES consensus_motif ( motif_id );

ALTER TABLE venn_view
    ADD CONSTRAINT venn_view_experiment_fk FOREIGN KEY ( experiment_experiment_id )
        REFERENCES experiment ( experiment_id );

ALTER TABLE venn_view
    ADD CONSTRAINT venn_view_motif_pos_fk FOREIGN KEY ( motif_pos_motifpos_id )
        REFERENCES motif_pos ( motifpos_id );

ALTER TABLE venn_view
    ADD CONSTRAINT venn_view_peak_fk FOREIGN KEY ( peak_peak_id )
        REFERENCES peak ( peak_id );

ALTER TABLE venn_view
    ADD CONSTRAINT venn_view_summit_fk FOREIGN KEY ( summit_summit_id )
        REFERENCES summit ( summit_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            16
-- CREATE INDEX                             0
-- ALTER TABLE                             33
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- ERRORS                                   6
-- WARNINGS                                 0
